#!/bin/bash

if [ -f "/detach_sess/.irssi" ]; then
rm -f /detach_sess/.irssi || true
sleep 1s
fi

dtach -n /detach_sess/.irssi /sbin/setuser abc /usr/bin/irssi --home=/config/.irssi 1>/dev/null


sleep 1s
