#!/usr/bin/with-contenv bash

if [ "$SSL_ENABLED" == "yes" ]
then
    DH="/config/nginx/dh.pem"
    DH_SIZE="2048"
    
    if [ ! -e "$DH" ]
    then
      echo ">> seems like the first start of nginx"
      echo ">> doing some preparations..."
      echo ""
    
      echo ">> generating $DH with size: $DH_SIZE"
      libressl dhparam -out "$DH" $DH_SIZE
    fi
    
    
    if [ ! -e "/config/nginx/cert.pem" ] || [ ! -e "/config/nginx/key.pem" ]
    then
      echo ">> generating self signed cert"
      libressl req -x509 -newkey rsa:4086 \
      -subj "/C=XX/ST=XXXX/L=XXXX/O=XXXX/CN=localhost" \
      -keyout "/config/nginx/key.pem" \
      -out "/config/nginx/cert.pem" \
      -days 3650 -nodes -sha256
    fi
    
    if [ ! -e "/config/nginx/conf.d/basic.conf" ] || [ ! -e "/config/nginx/conf.d/ssl.conf" ]
    then
     cp /defaults/conf.d/* /config/nginx/conf.d/
    fi
else
    exit 0
fi