#!/usr/bin/with-contenv bash

# Sanitize variables
SANED_VARS=( SSL_ENABLED )
for i in "${SANED_VARS[@]}"
do
  export echo "$i"="${!i//\"/}"
  export echo "$i"="$(echo "${!i}" | tr '[:upper:]' '[:lower:]')"
done

# make folders
mkdir -p /config/tmp /detach_sess

# copy config files/set links etc...
[[ ! -L /home/abc/.autodl ]] && ln -s /config/.autodl /home/abc/.autodl
[[ ! -L /config/.irssi/scripts/autorun/autodl-irssi.pl ]] && ln -s /config/.irssi/scripts/autodl-irssi.pl /config/.irssi/scripts/autorun/autodl-irssi.pl
[[ ! -f /config/.irssi/config ]] && cp /defaults/config.irssi /config/.irssi/config
[[ ! -f /config/.autodl/autodl.cfg ]] && cp /defaults/autodl.cfg /config/.autodl/autodl.cfg
[[ ! -f /usr/share/webapps/rutorrent/plugins/autodl-irssi/conf.php ]] && cp /defaults/conf.php /usr/share/webapps/rutorrent/plugins/autodl-irssi/conf.php
[[ ! -f /config/flood/config.js ]] && 
    if [ "$SSL_ENABLED" == "yes" ]
	then 
	  cp /defaults/config_ssl.js /config/flood/config.js
	else
	  cp /defaults/config.js /config/flood/config.js
	fi
[[ ! -L /usr/flood/config.js ]] && ln -s /config/flood/config.js /usr/flood/config.js && sed -i -e "s|<FLOOD_SECRET>|$FLOOD_SECRET|g" /config/flood/config.js && sed -i -e "s|<CONTEXT_PATH>|$CONTEXT_PATH|g" /config/flood/config.js

# set perms
chown abc:abc -R /config /detach_sess
chown abc:abc -R /usr/share/webapps/rutorrent
chown abc:abc /downloads
chmod 755 /usr/local/bin/curl