#!/usr/bin/with-contenv bash

usermod -s /bin/bash abc

# make folders
if [[ ! -d /config/.pyroscope ]];then
      su -c "mkdir -p /config/.pyroscope" abc
      su -c "mkdir -p /config/bin /config/.local" abc
      su -c 'git clone "https://github.com/pyroscope/pyrocore.git" /config/.local/pyroscope' abc
      su -c "echo 'export PYRO_CONFIG_DIR=/config/.pyroscope' >> /config/.profile" abc
      su -c "echo 'export PATH=$PATH:~/bin' >> /config/.profile" abc
      su -c '/config/.local/pyroscope/update-to-head.sh' abc
      su - -c '/config/bin/pyroadmin --create-config' abc
      su -c 'rm /config/.pyroscope/config.ini' abc
      su -c 'touch /config/.pyroscope/run/pyrotorque' abc
      su -c 'touch /config/.bash_completion' abc
      su -c 'grep /\.pyroscope/ /config/.bash_completion >/dev/null || echo >> /config/.bash_completion ". /config/.pyroscope/bash-completion.default"' abc
      su -c '. /config/.bash_completion' abc

fi

[[ ! -e /config/.pyroscope/config.ini ]] && \
        cp /defaults/config.ini /config/.pyroscope/config.ini

# permissions
chown -R abc:abc /config/.pyroscope
