#!/usr/bin/with-contenv bash

usermod -s /bin/bash abc

# make folders
if [[ ! -d /config/.pyroscope ]];then
      su -c "mkdir -p /config/.pyroscope" abc
      su -c "mkdir -p ~/bin ~/.local" abc
      su -c 'git clone "https://github.com/pyroscope/pyrocore.git" ~/.local/pyroscope' abc
      su -c "echo 'export PYRO_CONFIG_DIR=/config/.pyroscope' >> ~/.profile" abc
      su -c "echo 'export PATH=$PATH:~/bin' >> ~/.profile" abc
      su -c '~/.local/pyroscope/update-to-head.sh' abc
      su - -c '/config/bin/pyroadmin --create-config' abc
      su -c 'rm /config/.pyroscope/config.ini' abc
      su -c 'touch ~/.pyroscope/run/pyrotorque' abc
      su -c 'touch ~/.bash_completion' abc
      su -c 'grep /\.pyroscope/ ~/.bash_completion >/dev/null || echo >> /config/.bash_completion ". ~/.pyroscope/bash-completion.default"' abc
      su -c '. ~/.bash_completion' abc
      su -c "find /config/.pyroscope -type f |xargs sed -i 's/\~\//\/config\//g'" abc
fi

[[ ! -e /config/.pyroscope/config.ini ]] && \
        cp /defaults/config.ini /config/.pyroscope/config.ini

# permissions
chown -R abc:abc /config/.pyroscope
